<?php if($include_no == false){ ?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>c56</title>
    <link rel="stylesheet" href="../../../css/style.css">
  </head>
  <body>
<?php } ?>

  <section class="c56__container">
    <div class="container-fix">
      <div class="contador-ofertas-destacadas">
        <div class="texto"><b>20%</b> Reserva con el código <b>SPRINGH10</b></div>
        <div class="contador-holder">
          <div class="texto-top-holder">
            <div class="texto-top"><span></span> DÍAS</div>
          </div>
          <div class="contador" data-fecha-fin="2023/04/30">
            <div class="dias"></div>
            <div class="horas"></div>
            <div class="minutos"></div>
            <div class="segundos"></div>
          </div>
          <div class="texto-bottom-holder">
            <div class="texto-bottom">Date prisa, quedan menos de 24 horas</div>
          </div>
        </div>

        <div class="texto-posterior">
            Benefíciate de nuestras mejores ofertas y aprovecha el descuento del 20% gracias al código promocional.Puedes consultar las condiciones <a href="#" class="open-modal">aquí</a>.
        </div>


      </div>

    </div>
    
  </section>


  <div class="c56__container general_modal">
          <a href="#" class="btn-close"></a>
    
<!--          <div class="titulo-top-holder_">
            <div class="titulo-top_">Valoraciones</div>
          </div>-->
    
          
          <div class="modal-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi tellus, vulputate sed ipsum tristique, tempor ornare purus. Morbi tristique purus congue augue semper, a sagittis tortor auctor. Duis sagittis odio non sapien commodo mollis. Integer quis nisl ac orci ornare imperdiet a sed ex. Aliquam consectetur justo non lorem cursus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere, eros eget vestibulum auctor, nulla dui hendrerit nisl, id accumsan lectus neque et ligula. Maecenas vel lobortis urna. Vivamus vehicula urna in enim tempor dignissim. Pellentesque tristique odio eget nunc luctus elementum id cursus nulla. Pellentesque quis libero vehicula, consectetur libero at, finibus dui. Curabitur nulla arcu, hendrerit ut dictum et, efficitur eu ex. Phasellus quis ipsum diam. Curabitur id est mi. Donec suscipit velit tincidunt iaculis tempor.</p>

          </div>
          
        </div>



<?php if($include_no == false){ ?>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="../../../js/jquery.countdown.min.js"></script>
    <script src="../../../js/_c56.js"></script>
  </body>
</html>
<?php } ?>
